apiVersion: v1
kind: Service
metadata:
  name: mongodb-service
  namespace: mern-app
  labels:
    app.kubernetes.io/name: mongodb
    app.kubernetes.io/component: database
spec:
  selector:
    app: mongodb
  ports:
    - port: 27017
      targetPort: 27017
      name: mongodb
  type: ClusterIP
