apiVersion: v1
kind: ConfigMap
metadata:
  name: mern-config
  namespace: mern-app
  labels:
    app.kubernetes.io/name: mern-app
data:
  NODE_ENV: "production"
  PORT: "5000"
  HOST: "0.0.0.0"
  LOG_LEVEL: "info"
  MONGODB_HOST: "mongodb-service"
  MONGODB_PORT: "27017"
  MONGODB_DATABASE: "mern_k8s"
  CORS_ORIGIN: "http://frontend-service"
